version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5231:80"
    volumes:
      - image-storage:/app/images
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__WebApiDatabase=server=mysql;port=3306;database=musify;user=${MYSQL_ROOT_USER};password=${MYSQL_ROOT_PASSWORD}
      - ImageSettings__ImageFolderPath=/app/images
      - Jwt_Secret=${Jwt_Secret}
      - Jwt_Issuer=${Jwt_Issuer_Docker}
      - Jwt_Audience=${Jwt_Audience_Docker}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  image-storage:
  mysql-data:
