// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250215182907_AddReleaseYearToAlbum")]
    partial class AddReleaseYearToAlbum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Album_CreatedAt");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Album_Name");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Album_UpdatedAt");

                    b.ToTable("Albums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1c66a87-76f9-4894-a2e3-e0e03d7da038"),
                            CreatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(5922),
                            ImageLocation = "path/to/image1",
                            Name = "First Album",
                            ReleaseYear = 0,
                            UpdatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(5924)
                        },
                        new
                        {
                            Id = new Guid("6c5b4262-d2e3-4924-a2bc-6e6643c3c82b"),
                            CreatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(5927),
                            ImageLocation = "path/to/image2",
                            Name = "Second Album",
                            ReleaseYear = 0,
                            UpdatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(5927)
                        });
                });

            modelBuilder.Entity("Domain.AlbumArtistRelation", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("char(36)");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_AlbumArtistRelation_AlbumId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_AlbumArtistRelation_ArtistId");

                    b.ToTable("AlbumArtistRelations");

                    b.HasData(
                        new
                        {
                            AlbumId = new Guid("c1c66a87-76f9-4894-a2e3-e0e03d7da038"),
                            ArtistId = new Guid("ad70866f-8b2e-4a44-9e9e-fc11387ee4cc")
                        },
                        new
                        {
                            AlbumId = new Guid("c1c66a87-76f9-4894-a2e3-e0e03d7da038"),
                            ArtistId = new Guid("2ea18738-07ea-4d07-b3da-d4ab5f228c8d")
                        },
                        new
                        {
                            AlbumId = new Guid("6c5b4262-d2e3-4924-a2bc-6e6643c3c82b"),
                            ArtistId = new Guid("2ea18738-07ea-4d07-b3da-d4ab5f228c8d")
                        });
                });

            modelBuilder.Entity("Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Artist_CreatedAt");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Artist_Name");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Artist_UpdatedAt");

                    b.ToTable("Artists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad70866f-8b2e-4a44-9e9e-fc11387ee4cc"),
                            CreatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(6115),
                            ImageLocation = "path/to/image1",
                            Name = "First Artist",
                            UpdatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(6116)
                        },
                        new
                        {
                            Id = new Guid("2ea18738-07ea-4d07-b3da-d4ab5f228c8d"),
                            CreatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(6121),
                            ImageLocation = "path/to/image2",
                            Name = "Second Artist",
                            UpdatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(6121)
                        });
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<int>("PositionInAlbum")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_Song_AlbumId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Song_CreatedAt");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Song_Title");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Song_UpdatedAt");

                    b.HasIndex("Title", "AlbumId")
                        .HasDatabaseName("IX_Song_Title_AlbumId");

                    b.ToTable("Songs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc551ebc-5cb0-4792-bbdb-e431f221921f"),
                            AlbumId = new Guid("c1c66a87-76f9-4894-a2e3-e0e03d7da038"),
                            CreatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(6156),
                            Duration = new TimeSpan(0, 0, 3, 45, 0),
                            PositionInAlbum = -1,
                            Title = "First Song",
                            UpdatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(6157)
                        },
                        new
                        {
                            Id = new Guid("bf3d8fd2-e522-4a58-a73d-2ba26c323e82"),
                            AlbumId = new Guid("c1c66a87-76f9-4894-a2e3-e0e03d7da038"),
                            CreatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(6165),
                            Duration = new TimeSpan(0, 0, 4, 20, 0),
                            PositionInAlbum = -1,
                            Title = "Second Song",
                            UpdatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(6165)
                        },
                        new
                        {
                            Id = new Guid("6dbb4cab-45c3-4418-a8d8-ea234baddaed"),
                            AlbumId = new Guid("6c5b4262-d2e3-4924-a2bc-6e6643c3c82b"),
                            CreatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(6167),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            PositionInAlbum = -1,
                            Title = "Third Song",
                            UpdatedAt = new DateTime(2025, 2, 15, 18, 29, 7, 545, DateTimeKind.Utc).AddTicks(6167)
                        });
                });

            modelBuilder.Entity("Domain.SongArtistRelation", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("char(36)");

                    b.HasKey("SongId", "ArtistId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_SongArtistRelation_ArtistId");

                    b.HasIndex("SongId")
                        .HasDatabaseName("IX_SongArtistRelation_SongId");

                    b.ToTable("SongArtistRelations");

                    b.HasData(
                        new
                        {
                            SongId = new Guid("cc551ebc-5cb0-4792-bbdb-e431f221921f"),
                            ArtistId = new Guid("ad70866f-8b2e-4a44-9e9e-fc11387ee4cc")
                        },
                        new
                        {
                            SongId = new Guid("bf3d8fd2-e522-4a58-a73d-2ba26c323e82"),
                            ArtistId = new Guid("ad70866f-8b2e-4a44-9e9e-fc11387ee4cc")
                        },
                        new
                        {
                            SongId = new Guid("6dbb4cab-45c3-4418-a8d8-ea234baddaed"),
                            ArtistId = new Guid("2ea18738-07ea-4d07-b3da-d4ab5f228c8d")
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.AlbumArtistRelation", b =>
                {
                    b.HasOne("Domain.Album", "Album")
                        .WithMany("AlbumArtistRelations")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Artist", "Artist")
                        .WithMany("AlbumArtistRelations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.HasOne("Domain.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Domain.SongArtistRelation", b =>
                {
                    b.HasOne("Domain.Artist", "Artist")
                        .WithMany("SongArtistRelations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Song", "Song")
                        .WithMany("SongArtistRelations")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Domain.Album", b =>
                {
                    b.Navigation("AlbumArtistRelations");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Domain.Artist", b =>
                {
                    b.Navigation("AlbumArtistRelations");

                    b.Navigation("SongArtistRelations");
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.Navigation("SongArtistRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
