// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250214175932_AddIndexCreatedAtUpdatedAt")]
    partial class AddIndexCreatedAtUpdatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Album_CreatedAt");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Album_Name");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Album_UpdatedAt");

                    b.ToTable("Albums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("51c2241a-bab5-4906-b3ae-c31dfe7e4d64"),
                            CreatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9355),
                            ImageLocation = "path/to/image1",
                            Name = "First Album",
                            UpdatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9358)
                        },
                        new
                        {
                            Id = new Guid("75317369-1258-419c-ade8-692b5099cc2d"),
                            CreatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9361),
                            ImageLocation = "path/to/image2",
                            Name = "Second Album",
                            UpdatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9361)
                        });
                });

            modelBuilder.Entity("Domain.AlbumArtistRelation", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("char(36)");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_AlbumArtistRelation_AlbumId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_AlbumArtistRelation_ArtistId");

                    b.ToTable("AlbumArtistRelations");

                    b.HasData(
                        new
                        {
                            AlbumId = new Guid("51c2241a-bab5-4906-b3ae-c31dfe7e4d64"),
                            ArtistId = new Guid("4c77ab33-d2a9-45f7-91ab-9308502a4b4e")
                        },
                        new
                        {
                            AlbumId = new Guid("51c2241a-bab5-4906-b3ae-c31dfe7e4d64"),
                            ArtistId = new Guid("f363512f-5b08-4da5-9a63-565a9752780a")
                        },
                        new
                        {
                            AlbumId = new Guid("75317369-1258-419c-ade8-692b5099cc2d"),
                            ArtistId = new Guid("f363512f-5b08-4da5-9a63-565a9752780a")
                        });
                });

            modelBuilder.Entity("Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Artist_CreatedAt");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Artist_Name");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Artist_UpdatedAt");

                    b.ToTable("Artists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c77ab33-d2a9-45f7-91ab-9308502a4b4e"),
                            CreatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9516),
                            ImageLocation = "path/to/image1",
                            Name = "First Artist",
                            UpdatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9517)
                        },
                        new
                        {
                            Id = new Guid("f363512f-5b08-4da5-9a63-565a9752780a"),
                            CreatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9527),
                            ImageLocation = "path/to/image2",
                            Name = "Second Artist",
                            UpdatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9528)
                        });
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<int>("PositionInAlbum")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_Song_AlbumId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Song_CreatedAt");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Song_Title");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Song_UpdatedAt");

                    b.HasIndex("Title", "AlbumId")
                        .HasDatabaseName("IX_Song_Title_AlbumId");

                    b.ToTable("Songs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ef08cc2-33b0-4c3b-925b-68b2483a215c"),
                            AlbumId = new Guid("51c2241a-bab5-4906-b3ae-c31dfe7e4d64"),
                            CreatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9637),
                            Duration = new TimeSpan(0, 0, 3, 45, 0),
                            PositionInAlbum = -1,
                            Title = "First Song",
                            UpdatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9637)
                        },
                        new
                        {
                            Id = new Guid("dc2a5a61-c8a9-48ab-85d2-8f6e05576d83"),
                            AlbumId = new Guid("51c2241a-bab5-4906-b3ae-c31dfe7e4d64"),
                            CreatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9645),
                            Duration = new TimeSpan(0, 0, 4, 20, 0),
                            PositionInAlbum = -1,
                            Title = "Second Song",
                            UpdatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9646)
                        },
                        new
                        {
                            Id = new Guid("2499f354-eea1-45ff-9f1c-d6fc6cb717c2"),
                            AlbumId = new Guid("75317369-1258-419c-ade8-692b5099cc2d"),
                            CreatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9648),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            PositionInAlbum = -1,
                            Title = "Third Song",
                            UpdatedAt = new DateTime(2025, 2, 14, 17, 59, 31, 959, DateTimeKind.Utc).AddTicks(9649)
                        });
                });

            modelBuilder.Entity("Domain.SongArtistRelation", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("char(36)");

                    b.HasKey("SongId", "ArtistId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_SongArtistRelation_ArtistId");

                    b.HasIndex("SongId")
                        .HasDatabaseName("IX_SongArtistRelation_SongId");

                    b.ToTable("SongArtistRelations");

                    b.HasData(
                        new
                        {
                            SongId = new Guid("2ef08cc2-33b0-4c3b-925b-68b2483a215c"),
                            ArtistId = new Guid("4c77ab33-d2a9-45f7-91ab-9308502a4b4e")
                        },
                        new
                        {
                            SongId = new Guid("dc2a5a61-c8a9-48ab-85d2-8f6e05576d83"),
                            ArtistId = new Guid("4c77ab33-d2a9-45f7-91ab-9308502a4b4e")
                        },
                        new
                        {
                            SongId = new Guid("2499f354-eea1-45ff-9f1c-d6fc6cb717c2"),
                            ArtistId = new Guid("f363512f-5b08-4da5-9a63-565a9752780a")
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.AlbumArtistRelation", b =>
                {
                    b.HasOne("Domain.Album", "Album")
                        .WithMany("AlbumArtistRelations")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Artist", "Artist")
                        .WithMany("AlbumArtistRelations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.HasOne("Domain.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Domain.SongArtistRelation", b =>
                {
                    b.HasOne("Domain.Artist", "Artist")
                        .WithMany("SongArtistRelations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Song", "Song")
                        .WithMany("SongArtistRelations")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Domain.Album", b =>
                {
                    b.Navigation("AlbumArtistRelations");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Domain.Artist", b =>
                {
                    b.Navigation("AlbumArtistRelations");

                    b.Navigation("SongArtistRelations");
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.Navigation("SongArtistRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
