// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250214135732_UserChangeUserNameToEmail")]
    partial class UserChangeUserNameToEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Album_Name");

                    b.ToTable("Albums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("db212c47-9094-4e92-a330-2b92ecfab502"),
                            CreatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7242),
                            ImageLocation = "path/to/image1",
                            Name = "First Album",
                            UpdatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7245)
                        },
                        new
                        {
                            Id = new Guid("5e43cf16-0657-42ed-baca-a9c7936bd5a6"),
                            CreatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7249),
                            ImageLocation = "path/to/image2",
                            Name = "Second Album",
                            UpdatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7249)
                        });
                });

            modelBuilder.Entity("Domain.AlbumArtistRelation", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("char(36)");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_AlbumArtistRelation_AlbumId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_AlbumArtistRelation_ArtistId");

                    b.ToTable("AlbumArtistRelations");

                    b.HasData(
                        new
                        {
                            AlbumId = new Guid("db212c47-9094-4e92-a330-2b92ecfab502"),
                            ArtistId = new Guid("795c69d9-1759-4f4a-ba78-de2d240b7245")
                        },
                        new
                        {
                            AlbumId = new Guid("db212c47-9094-4e92-a330-2b92ecfab502"),
                            ArtistId = new Guid("b7410454-ed69-4403-a699-9f7e6b9a307d")
                        },
                        new
                        {
                            AlbumId = new Guid("5e43cf16-0657-42ed-baca-a9c7936bd5a6"),
                            ArtistId = new Guid("b7410454-ed69-4403-a699-9f7e6b9a307d")
                        });
                });

            modelBuilder.Entity("Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Artist_Name");

                    b.ToTable("Artists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("795c69d9-1759-4f4a-ba78-de2d240b7245"),
                            CreatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7469),
                            ImageLocation = "path/to/image1",
                            Name = "First Artist",
                            UpdatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7469)
                        },
                        new
                        {
                            Id = new Guid("b7410454-ed69-4403-a699-9f7e6b9a307d"),
                            CreatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7475),
                            ImageLocation = "path/to/image2",
                            Name = "Second Artist",
                            UpdatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7475)
                        });
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<int>("PositionInAlbum")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_Song_AlbumId");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Song_Title");

                    b.HasIndex("Title", "AlbumId")
                        .HasDatabaseName("IX_Song_Title_AlbumId");

                    b.ToTable("Songs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("29f71f05-fc76-428b-9591-7b5cb5bafb5a"),
                            AlbumId = new Guid("db212c47-9094-4e92-a330-2b92ecfab502"),
                            CreatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7518),
                            Duration = new TimeSpan(0, 0, 3, 45, 0),
                            PositionInAlbum = -1,
                            Title = "First Song",
                            UpdatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7519)
                        },
                        new
                        {
                            Id = new Guid("a3cc1977-15f0-48b8-bda5-cf7b1b700821"),
                            AlbumId = new Guid("db212c47-9094-4e92-a330-2b92ecfab502"),
                            CreatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7526),
                            Duration = new TimeSpan(0, 0, 4, 20, 0),
                            PositionInAlbum = -1,
                            Title = "Second Song",
                            UpdatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7527)
                        },
                        new
                        {
                            Id = new Guid("e2066fc3-35bd-4b8a-b565-12cfdaef47e8"),
                            AlbumId = new Guid("5e43cf16-0657-42ed-baca-a9c7936bd5a6"),
                            CreatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7529),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            PositionInAlbum = -1,
                            Title = "Third Song",
                            UpdatedAt = new DateTime(2025, 2, 14, 13, 57, 31, 822, DateTimeKind.Utc).AddTicks(7530)
                        });
                });

            modelBuilder.Entity("Domain.SongArtistRelation", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("char(36)");

                    b.HasKey("SongId", "ArtistId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_SongArtistRelation_ArtistId");

                    b.HasIndex("SongId")
                        .HasDatabaseName("IX_SongArtistRelation_SongId");

                    b.ToTable("SongArtistRelations");

                    b.HasData(
                        new
                        {
                            SongId = new Guid("29f71f05-fc76-428b-9591-7b5cb5bafb5a"),
                            ArtistId = new Guid("795c69d9-1759-4f4a-ba78-de2d240b7245")
                        },
                        new
                        {
                            SongId = new Guid("a3cc1977-15f0-48b8-bda5-cf7b1b700821"),
                            ArtistId = new Guid("795c69d9-1759-4f4a-ba78-de2d240b7245")
                        },
                        new
                        {
                            SongId = new Guid("e2066fc3-35bd-4b8a-b565-12cfdaef47e8"),
                            ArtistId = new Guid("b7410454-ed69-4403-a699-9f7e6b9a307d")
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.AlbumArtistRelation", b =>
                {
                    b.HasOne("Domain.Album", "Album")
                        .WithMany("AlbumArtistRelations")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Artist", "Artist")
                        .WithMany("AlbumArtistRelations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.HasOne("Domain.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Domain.SongArtistRelation", b =>
                {
                    b.HasOne("Domain.Artist", "Artist")
                        .WithMany("SongArtistRelations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Song", "Song")
                        .WithMany("SongArtistRelations")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Domain.Album", b =>
                {
                    b.Navigation("AlbumArtistRelations");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Domain.Artist", b =>
                {
                    b.Navigation("AlbumArtistRelations");

                    b.Navigation("SongArtistRelations");
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.Navigation("SongArtistRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
