// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250213202602_AddCreatedUpdatedAtToAlbumSongUser")]
    partial class AddCreatedUpdatedAtToAlbumSongUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Album_Name");

                    b.ToTable("Albums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d29240d-dbef-4b2c-8b3e-63c72ca6ecf4"),
                            CreatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(3876),
                            ImageLocation = "path/to/image1",
                            Name = "First Album",
                            UpdatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(3878)
                        },
                        new
                        {
                            Id = new Guid("bca35c96-417d-4a05-b71c-9321897e3e94"),
                            CreatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(3882),
                            ImageLocation = "path/to/image2",
                            Name = "Second Album",
                            UpdatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(3882)
                        });
                });

            modelBuilder.Entity("Domain.AlbumArtistRelation", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("char(36)");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_AlbumArtistRelation_AlbumId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_AlbumArtistRelation_ArtistId");

                    b.ToTable("AlbumArtistRelations");

                    b.HasData(
                        new
                        {
                            AlbumId = new Guid("3d29240d-dbef-4b2c-8b3e-63c72ca6ecf4"),
                            ArtistId = new Guid("c89dad75-9826-43e3-9d7d-3b8c0823281b")
                        },
                        new
                        {
                            AlbumId = new Guid("3d29240d-dbef-4b2c-8b3e-63c72ca6ecf4"),
                            ArtistId = new Guid("807bddea-7d0e-4d08-a7f2-b65dc5d12309")
                        },
                        new
                        {
                            AlbumId = new Guid("bca35c96-417d-4a05-b71c-9321897e3e94"),
                            ArtistId = new Guid("807bddea-7d0e-4d08-a7f2-b65dc5d12309")
                        });
                });

            modelBuilder.Entity("Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Artist_Name");

                    b.ToTable("Artists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c89dad75-9826-43e3-9d7d-3b8c0823281b"),
                            CreatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(4018),
                            ImageLocation = "path/to/image1",
                            Name = "First Artist",
                            UpdatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(4018)
                        },
                        new
                        {
                            Id = new Guid("807bddea-7d0e-4d08-a7f2-b65dc5d12309"),
                            CreatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(4030),
                            ImageLocation = "path/to/image2",
                            Name = "Second Artist",
                            UpdatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(4030)
                        });
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<int>("PositionInAlbum")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_Song_AlbumId");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Song_Title");

                    b.HasIndex("Title", "AlbumId")
                        .HasDatabaseName("IX_Song_Title_AlbumId");

                    b.ToTable("Songs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77cd3df6-36bd-4d75-a892-ff6bb3c12c52"),
                            AlbumId = new Guid("3d29240d-dbef-4b2c-8b3e-63c72ca6ecf4"),
                            CreatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(4061),
                            Duration = new TimeSpan(0, 0, 3, 45, 0),
                            PositionInAlbum = -1,
                            Title = "First Song",
                            UpdatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(4062)
                        },
                        new
                        {
                            Id = new Guid("1477bed5-ec5f-49d8-af90-3ba79752ecb2"),
                            AlbumId = new Guid("3d29240d-dbef-4b2c-8b3e-63c72ca6ecf4"),
                            CreatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(4070),
                            Duration = new TimeSpan(0, 0, 4, 20, 0),
                            PositionInAlbum = -1,
                            Title = "Second Song",
                            UpdatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(4071)
                        },
                        new
                        {
                            Id = new Guid("911de022-884e-44a2-8b43-b3b951cddee7"),
                            AlbumId = new Guid("bca35c96-417d-4a05-b71c-9321897e3e94"),
                            CreatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(4073),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            PositionInAlbum = -1,
                            Title = "Third Song",
                            UpdatedAt = new DateTime(2025, 2, 13, 20, 26, 1, 492, DateTimeKind.Utc).AddTicks(4073)
                        });
                });

            modelBuilder.Entity("Domain.SongArtistRelation", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("char(36)");

                    b.HasKey("SongId", "ArtistId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_SongArtistRelation_ArtistId");

                    b.HasIndex("SongId")
                        .HasDatabaseName("IX_SongArtistRelation_SongId");

                    b.ToTable("SongArtistRelations");

                    b.HasData(
                        new
                        {
                            SongId = new Guid("77cd3df6-36bd-4d75-a892-ff6bb3c12c52"),
                            ArtistId = new Guid("c89dad75-9826-43e3-9d7d-3b8c0823281b")
                        },
                        new
                        {
                            SongId = new Guid("1477bed5-ec5f-49d8-af90-3ba79752ecb2"),
                            ArtistId = new Guid("c89dad75-9826-43e3-9d7d-3b8c0823281b")
                        },
                        new
                        {
                            SongId = new Guid("911de022-884e-44a2-8b43-b3b951cddee7"),
                            ArtistId = new Guid("807bddea-7d0e-4d08-a7f2-b65dc5d12309")
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.AlbumArtistRelation", b =>
                {
                    b.HasOne("Domain.Album", "Album")
                        .WithMany("AlbumArtistRelations")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Artist", "Artist")
                        .WithMany("AlbumArtistRelations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.HasOne("Domain.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Domain.SongArtistRelation", b =>
                {
                    b.HasOne("Domain.Artist", "Artist")
                        .WithMany("SongArtistRelations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Song", "Song")
                        .WithMany("SongArtistRelations")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Domain.Album", b =>
                {
                    b.Navigation("AlbumArtistRelations");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Domain.Artist", b =>
                {
                    b.Navigation("AlbumArtistRelations");

                    b.Navigation("SongArtistRelations");
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.Navigation("SongArtistRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
