// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Album_Name");

                    b.ToTable("Albums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcfdc9e8-fdd7-4f00-b398-11e9b757ddce"),
                            ImageLocation = "path/to/image1",
                            Name = "First Album"
                        },
                        new
                        {
                            Id = new Guid("2f227d3d-473f-4bfb-8f77-2400ddeba03b"),
                            ImageLocation = "path/to/image2",
                            Name = "Second Album"
                        });
                });

            modelBuilder.Entity("Domain.AlbumArtistRelation", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("char(36)");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_AlbumArtistRelation_AlbumId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_AlbumArtistRelation_ArtistId");

                    b.ToTable("AlbumArtistRelations");

                    b.HasData(
                        new
                        {
                            AlbumId = new Guid("bcfdc9e8-fdd7-4f00-b398-11e9b757ddce"),
                            ArtistId = new Guid("144b3ba5-03df-4ea3-abde-9fff51549409")
                        },
                        new
                        {
                            AlbumId = new Guid("bcfdc9e8-fdd7-4f00-b398-11e9b757ddce"),
                            ArtistId = new Guid("866f690b-f411-4ebc-8ff6-f64d8bbbbe6c")
                        },
                        new
                        {
                            AlbumId = new Guid("2f227d3d-473f-4bfb-8f77-2400ddeba03b"),
                            ArtistId = new Guid("866f690b-f411-4ebc-8ff6-f64d8bbbbe6c")
                        });
                });

            modelBuilder.Entity("Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Artist_Name");

                    b.ToTable("Artists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("144b3ba5-03df-4ea3-abde-9fff51549409"),
                            CreatedAt = new DateTime(2025, 2, 12, 18, 15, 36, 285, DateTimeKind.Utc).AddTicks(2461),
                            ImageLocation = "path/to/image1",
                            Name = "First Artist",
                            UpdatedAt = new DateTime(2025, 2, 12, 18, 15, 36, 285, DateTimeKind.Utc).AddTicks(2463)
                        },
                        new
                        {
                            Id = new Guid("866f690b-f411-4ebc-8ff6-f64d8bbbbe6c"),
                            CreatedAt = new DateTime(2025, 2, 12, 18, 15, 36, 285, DateTimeKind.Utc).AddTicks(2471),
                            ImageLocation = "path/to/image2",
                            Name = "Second Artist",
                            UpdatedAt = new DateTime(2025, 2, 12, 18, 15, 36, 285, DateTimeKind.Utc).AddTicks(2471)
                        });
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<int>("PositionInAlbum")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("IX_Song_AlbumId");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Song_Title");

                    b.HasIndex("Title", "AlbumId")
                        .HasDatabaseName("IX_Song_Title_AlbumId");

                    b.ToTable("Songs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d489738-ab06-41dd-8b8f-796496a62a91"),
                            AlbumId = new Guid("bcfdc9e8-fdd7-4f00-b398-11e9b757ddce"),
                            Duration = new TimeSpan(0, 0, 3, 45, 0),
                            PositionInAlbum = -1,
                            Title = "First Song"
                        },
                        new
                        {
                            Id = new Guid("e5f95f6c-f847-4306-9cd3-5ce5abe54a3f"),
                            AlbumId = new Guid("bcfdc9e8-fdd7-4f00-b398-11e9b757ddce"),
                            Duration = new TimeSpan(0, 0, 4, 20, 0),
                            PositionInAlbum = -1,
                            Title = "Second Song"
                        },
                        new
                        {
                            Id = new Guid("4170612e-38f0-46a9-9d6c-ed99e88bceb5"),
                            AlbumId = new Guid("2f227d3d-473f-4bfb-8f77-2400ddeba03b"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            PositionInAlbum = -1,
                            Title = "Third Song"
                        });
                });

            modelBuilder.Entity("Domain.SongArtistRelation", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("char(36)");

                    b.HasKey("SongId", "ArtistId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_SongArtistRelation_ArtistId");

                    b.HasIndex("SongId")
                        .HasDatabaseName("IX_SongArtistRelation_SongId");

                    b.ToTable("SongArtistRelations");

                    b.HasData(
                        new
                        {
                            SongId = new Guid("7d489738-ab06-41dd-8b8f-796496a62a91"),
                            ArtistId = new Guid("144b3ba5-03df-4ea3-abde-9fff51549409")
                        },
                        new
                        {
                            SongId = new Guid("e5f95f6c-f847-4306-9cd3-5ce5abe54a3f"),
                            ArtistId = new Guid("144b3ba5-03df-4ea3-abde-9fff51549409")
                        },
                        new
                        {
                            SongId = new Guid("4170612e-38f0-46a9-9d6c-ed99e88bceb5"),
                            ArtistId = new Guid("866f690b-f411-4ebc-8ff6-f64d8bbbbe6c")
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'UUID()'");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.AlbumArtistRelation", b =>
                {
                    b.HasOne("Domain.Album", "Album")
                        .WithMany("AlbumArtistRelations")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Artist", "Artist")
                        .WithMany("AlbumArtistRelations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.HasOne("Domain.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Domain.SongArtistRelation", b =>
                {
                    b.HasOne("Domain.Artist", "Artist")
                        .WithMany("SongArtistRelations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Song", "Song")
                        .WithMany("SongArtistRelations")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Domain.Album", b =>
                {
                    b.Navigation("AlbumArtistRelations");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Domain.Artist", b =>
                {
                    b.Navigation("AlbumArtistRelations");

                    b.Navigation("SongArtistRelations");
                });

            modelBuilder.Entity("Domain.Song", b =>
                {
                    b.Navigation("SongArtistRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
