<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="FFMpegCore" Version="5.2.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Search\Search.Variant1.Pagination\Search.Variant1.Pagination.csproj" />
    <ProjectReference Include="..\Search\Search.Variant2_1.LevenshteinBasic\Search.Variant2_1.LevenshteinBasic.csproj" />
    <ProjectReference Include="..\Search\Search.Variant2_2.LevenshteinStack\Search.Variant2_2.LevenshteinStack.csproj" />
    <ProjectReference Include="..\Search\Search.Variant3_1.DamerauBasic\Search.Variant3_1.DamerauBasic.csproj" />
    <ProjectReference Include="..\Search\Search.Variant3_2.DamerauStack\Search.Variant3_2.DamerauStack.csproj" />
    <ProjectReference Include="..\Search\Search.Variant3_3.DamerauBitmap\Search.Variant3_3.DamerauBitmap.csproj" />
    <ProjectReference Include="..\Search\Search.Variant4_1.FstAutomaton\Search.Variant4_1.FstAutomaton.csproj" />
    <ProjectReference Include="..\Search\Search.Variant4_2.FstAutomaton\Search.Variant4_2.FstAutomaton.csproj" />
  </ItemGroup>

</Project>
